name: Laravel Tests

on:
  push:
    branches: ["*"]
  pull_request:
    branches: ["*"]

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      # Clonar el repositorio en la ra√≠z
      - uses: actions/checkout@v4
        with:
          path: .
      # Configurar PHP
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.2"
          extensions: mbstring, pdo, pdo_sqlite

      # Instalar dependencias
      - name: Install dependencies
        run: composer install --no-interaction --prefer-dist

      # Preparar el entorno de pruebas
      - name: Prepare environment
        run: |
          cp .env.testing .env
          php artisan key:generate

      # Ejecutar los tests de Laravel
      - name: Run tests
        run: php artisan test
